import type { Metadata } from "next";
import { Poiret_One, Inter } from "next/font/google";
import "./globals.css";

const poiret = Poiret_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poiret",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poiret.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
